name: example
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: '>=2.1.0 <3.0.0'

publish_to: none

dependencies:
  flutter:
    sdk: flutter
  circular_countdown:
    path: ../
  gap:

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
